# Generated by Django 6.0.3 on 2026-03-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('orgao_expedidor', models.CharField(max_length=50)),
                ('data_expedicao_rg', models.DateField()),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('raca_cor', models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena'), ('nao_declarada', 'Não declarada')], max_length=20)),
                ('pcd', models.BooleanField(default=False)),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_mae', models.CharField(max_length=200)),
                ('naturalidade', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_alunos/')),
            ],
        ),
    ]
