# Generated by Django 6.0.3 on 2026-03-24 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_curso_polo_aluno_ativo_disciplina_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cursando', 'Cursando')], max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.disciplina')),
            ],
        ),
    ]
